version: '3'
services:
  node_app:
    platform: linux/arm64
    entrypoint:
      - npx
      - parcel
      - src/index.html
    build:
      context: .
      target: runner
      dockerfile: ./Dockerfile
    ports:
      - 1234:1234
    volumes:
      - ~/.ssh/ionos:/com.docker.devenvironments.code/auth/sshkey
