version: '3'
services:
  node_app:
    platform: linux/arm64
    entrypoint:
      - sleep
      - infinity
    build:
      context: .
      target: runner
      dockerfile: ./Dockerfile
    volumes:
      - ~/.ssh/ionos:./auth
