version: '3'
services:
  node_app:
    platform: linux/arm64
    build:
      context: .
      target: runner
    entrypoint:
      - sh
      - -c
      - cd /com.docker.devenvironments.code && npm run dev
    ports:
      # I know it should probably be illegal to solve a problem like this. But I could't get it to work otherwise.
      # When starting the DevEnv it starts up a "normal" Docker container. Then opening in VSCode starts a new one which tries to also use port 1234 that is obviously taken by the first one.
      # So to use 1234 for the second container (the one that is important) I just do -1.
      # I know, im sorry.
      - 1233:1234
    volumes:
      - ~/.ssh/ionos:/com.docker.devenvironments.code/auth/sshkey
