version: '3'
services:
  node_app:
    platform: linux/arm64
    entrypoint:
      - sh
      - -c
      - npm run dev
    build:
      context: .
      target: runner
      dockerfile: ./Dockerfile
    ports:
      - 80:1234
    volumes:
      - ~/.ssh/ionos:/com.docker.devenvironments.code/auth/sshkey
      - ./app:/app
